### ISSUE TITLE
Conversion or region list to numpy array break compatibility with Astropy Regions

### ISSUE THREAD

**Issue by conormcp** [astroweaver/the_farmer#7]
The conversion of `regs` to a numpy array in this line in not needed and breaks compatibility with [Astropy Regions](https://github.com/astropy/regions). 

https://github.com/astroweaver/the_farmer/blob/81361c74dddf19d6efe9a5e957f265cfe36819eb/farmer/utils.py#L809-L821

Removing this line should solve the issue.

https://github.com/astroweaver/the_farmer/blob/81361c74dddf19d6efe9a5e957f265cfe36819eb/farmer/utils.py#L819

**Comment by astroweaver** [comment]
Thanks for the find, Conor! I've pushed an update to fix this.
